---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq
spec:
  hard:
    limits.cpu: "2"
    limits.memory: "4Gi"
    requests.cpu: "2"
    requests.memory: "4Gi"
    pods: "10"
    services: "5"
